### ISSUE TITLE
`NoClassDefFoundError` with kotlinx.datetime 0.7.1

### ISSUE THREAD

**Issue by GSala** [TelemetryDeck/KotlinSDK#90]
When bumping the project to use kotlinx.datetime to 0.7.1, I get the following `NoClassDefFoundError`:

```
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/datetime/Clock$System;
    at com.telemetrydeck.sdk.providers.CalendarParameterProvider.enrich(CalendarParameterProvider.kt:48)
    at com.telemetrydeck.sdk.TelemetryDeck.createSignal(TelemetryDeck.kt:274)
    at com.telemetrydeck.sdk.TelemetryDeck.signal(TelemetryDeck.kt:138)
    at com.telemetrydeck.sdk.TelemetryDeck.processSignal(TelemetryDeck.kt:128)
    at com.telemetrydeck.sdk.TelemetryDeckSignalProcessor$DefaultImpls.processSignal$default(TelemetryDeckSignalProcessor.kt:50)
    at com.telemetrydeck.sdk.providers.SessionTrackingSignalProvider.startSession(SessionTrackingSignalProvider.kt:297)
    at com.telemetrydeck.sdk.providers.SessionTrackingSignalProvider.handleOnForeground(SessionTrackingSignalProvider.kt:145)
```

## Cause 

https://github.com/Kotlin/kotlinx-datetime?tab=readme-ov-file#deprecation-of-instant
`Instant` and `Clock` have been moved to the Kotlin standard library as of Kotlin 2.2.0 and kotlinx.datetime 0.7.0

## Workaround
Use compat version `0.7.1-0.6.x-compat` until this SDK updates their dependencies.

**Comment by kkostov** [comment]
Thanks for the detailed report folks!
We are preparing to adopt Kotlin 2.2+ for the SDK which will also include a fix for this problem.

**Comment by hypePG** [comment]
hello, any news on this?

**Comment by kkostov** [comment]
Hi @hypePG - we're working on a new version of the KotlinSDK that will have this sorted out. I will keep you posted!

**Comment by kkostov** [comment]
Fixed in #109
